sakeel-103/DFS-BFS-Graph-Travers

- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/main-index/main-index.component.html
I have added functionality in the navbar for travelling between bfs and dfs pages and the main index page
> Added Navbar functionality

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
Algorithm Description has been added. One can open it hitting the algorithm description button
> Added description for algorithms as a card

- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
Now on input custom graph will be generated. Although there is a format specified. Please test and tell me if changes are necessary
> Added custom graph creation feature

- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
Reverts sakeel-103/DFS-BFS-Graph-Travers#9
> Revert "Revert "Added custom graph creation feature""

- package-lock.json
- package.json
- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
The clear feature is implemented and minor css has been added to increase aesthetic value
> Form aesthetic upgraded and clear feature implemented

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
I fixed the explore button redirect issue and also improved the style of homepage(header file) by changing background, adding hover effect etc.
resolves issue #11
> fixed the explore button and improved the style of homepage.

- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
https://github.com/user-attachments/assets/27322cbf-1473-4cd2-9ea6-c8e2e25a6c60
@sakeel-103 
This feature has been implemented
> Added scroll feature

- backend/package.json
> Correct server file name

- backend/server.js
> Send json response string after User is created in db

- backend/middlewares/authenticate.js
- backend/middlewares/validation.js
- backend/server.js
> Add auth and signup validate middlewares

- .gitignore
- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
**Resolved Login Functionality:** 
issue number #38  @sakeel-103 
The _login button in the HTML was previously not properly linked to the TypeScript file, _resulting in an unintended direct redirect_.__ **This has been fixed to ensure that the login button now correctly triggers the authentication process before redirecting the user.**
**Improved Authentication Logic:**
The login process **now checks for user credentials stored in local storage**. This enhancement allows the application to **authenticate users based on data added by the signup page**, ensuring that both login and signup functionalities work together effectively.
The authenticate method now verifies user credentials against 
users array stored in local storage, providing a more dynamic and flexible authentication …
> Fix Login  Functionality and Redirect Logic

- .gitignore
- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
Pull Request Description issue #38  @sakeel-103 
This pull request addresses the following changes:
Resolved earlier conflicts with the backend to ensure seamless integration.
**Updated the frontend login functionality to work correctly with local storage authentication, allowing users to log in without credentials.**
Implemented a check to prevent users from progressing until successful login verification.
Please review the changes and let me know if any further adjustments are needed!
**Connected the TypeScript logic to the form submission,** specifically ensuring that the line 
`<form id="loginForm" #form="ngForm" (ngSubmit)="login(form)"> is now functional.`
**Added the following code logic for login**:
typescript
Copy code
```
login(form: NgForm) {
if (form.valid) {
const userData = …
```
> Fix: Resolve Backend Conflict and Enhance Frontend Login Functionality

- backend/server.js
> Add an environment variable to allow easier adjustments of hash password

- backend/server.js
> Implement a graceful shutdown

- src/app/components/main-index/main-index.component.css
- src/app/components/main-index/main-index.component.html
#33 To improve the UI/UX design for your Graph Traversal page, adding the matter of the Dfs and Bfs.
> Improve UI/UX Design for Graph Traversal Page

- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
> Make canvas scrollable and adjust height according to max depth of DFS

- .gitignore
- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
Reverts sakeel-103/DFS-BFS-Graph-Travers#42
As the signup/login form functionality is not working correctly, please correct the code and then push your commits.
> Revert "Fix Login  Functionality and Redirect Logic"

- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
- src/app/components/signup-page/signup-page.component.css
- src/app/components/signup-page/signup-page.component.html
- src/app/components/signup-page/signup-page.component.ts
#39
This directs to home page
this directs to sign-up page
please also level the points
> Made all the go back option and close option in login page

- src/app/components/signup-page/signup-page.component.html
> Fixed the overlapping of welcome text and container

- angular.json
- backend/middlewares/authenticate.js
- backend/package.json
- backend/server.js
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
- src/app/components/login-page/login-page.component.html
- src/app/components/main-index/main-index.component.css
- src/app/components/main-index/main-index.component.html
- src/app/components/main-index/main-index.component.ts
- src/app/services/auth.service.ts
> Added logout button and new route in backend

- angular.json
- backend/package-lock.json
- package.json
- src/app/components/signup-page/signup-page.component.ts
- src/app/services/auth.service.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Fix issue #59 and also remove the password storing functionality from localStorage, and create environment files for better configuration."
https://github.com/user-attachments/assets/4df67b19-834a-44b0-9297-288aa54bc6eb
> fix api endpoints and data leaking

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
> Make bfs canvas scrollable

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
fix: #83
https://github.com/user-attachments/assets/265e40f0-4988-4a7c-ad55-c6ccc114fd71
> Revamp BFS and DFS page and removed inconsistent buttons on the page 

- src/app/components/main-index/main-index.component.html
#70 
The changes ensure that clicking the logout button triggers the appropriate action to clear the user session and handle any necessary backend interactions.
https://github.com/user-attachments/assets/fd99f9ca-8aea-4cd3-af4c-cfe627d46fd9
> Logout Button Not Functioning Properly

- src/app/components/signup-page/signup-page.component.ts
on successful sign up now the page navigates to the login page 
fix: #65
> add navigation to login page on succcessful sign up

- src/app/components/main-index/main-index.component.html
> Add logout function in main index page

- src/app/app.component.ts
- src/app/app.routes.ts
- src/app/components/aboutUs-page/aboutUs.component.css
- src/app/components/aboutUs-page/aboutUs.component.html
- src/app/components/aboutUs-page/aboutUs.component.ts
- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
fix #58
https://github.com/user-attachments/assets/094a33d4-eeb9-4693-9ec7-a655470770c9
> Add about us page and fix navbar

- backend/package-lock.json
- backend/package.json
- package-lock.json
- package.json
- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
@sakeel-103 As you asked i changed the UI into lighter shades 
Issue no #71 
And also please add gssoc-ext and hacktoberfest-accepted s
> Enhanced UI , Header and Footer (Lighter Shades)

- src/app/components/main-index/main-index.component.css
#94 
Made the Navbar stick to top when page is scrolled and all content shall scroll under it.
Also alligned the nav items center vertically
> Made Navbar sticky to top

- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.ts
closes #77 
---
---
- Click on Reset BFS
---
---
- Click on Reset DFS
> Clear graph canvas when clicked on reset BFS / DFS

- backend/server.js
Proper error handling is critical in any production app. Centralized error handling improves readability and maintainability. Successfully added the CEH @sakeel-103 please also add the required gssoc labels thank you
issue #62
> Added Centralized Error Handling

- src/app/components/header/header.component.html
- src/app/components/header/style.css
fix=: #103 
hey @sakeel-103 i did my best if possible can you award me with level 3
> Revamped Landing Page

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/main-index/main-index.component.css
- src/app/components/main-index/main-index.component.html
> Fix header styling

- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
- src/app/components/signup-page/signup-page.component.html
- src/app/components/signup-page/signup-page.component.ts
> Add Pass Viewer

- src/app/app.routes.ts
- src/app/components/faq/faq.component.css
- src/app/components/faq/faq.component.html
- src/app/components/faq/faq.component.spec.ts
- src/app/components/faq/faq.component.ts
- src/app/components/header/header.component.html
- src/app/components/main-index/main-index.component.html
> Add faq page to the application 

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
> Add dropdown to profile button on bfs and dfs page 

- backend/models/weightedgraph.js
- backend/server.js
Implemented a new /api/dijkstra route that calculates the shortest paths using Dijkstra's algorithm.
The endpoint accepts a weighted graph and a starting node in the request body and returns the shortest distances to all other nodes.
Enhanced the backend to handle graph traversal efficiently.
Existing features like user authentication and session management remain unchanged.
closes #110
> Add Dijkstra's Algorithm and Backend IntegrationNew

- src/index.html
@sakeel-103 
I have added scroll to top feature
https://github.com/user-attachments/assets/e9045d46-19cb-4b97-8ef4-2229199f66da
#120
> added scroll-to-top feature

- src/app/app.component.ts
- src/app/components/aboutUs-page/aboutUs.component.html
- src/app/components/aboutUs-page/aboutUs.component.ts
- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
- src/app/components/main-index/main-index.component.html
- src/app/components/main-index/main-index.component.ts
- src/app/components/navbar/navbar.component.css
- src/app/components/navbar/navbar.component.html
- src/app/components/navbar/navbar.component.spec.ts
- src/app/components/navbar/navbar.component.ts
fix: #123 
Hey @sakeel-103 please merge PR 113,115 as this will not case any conflicts then, after merging the two PRs then merge 124
> ADD Comman Navbar component throught the application

- backend/server.js
**Changes Introduced:**
1. **Session Security Enhancements:**
(a) Implemented secure cookie settings:
-Set httpOnly to prevent client-side access to cookies.
-Set secure to true when in production, ensuring cookies are only sent over HTTPS.
(b) Ensured better session management for improved security during user interactions.
These updates help protect user sessions and reduce potential vulnerabilities.
> Enhance Session Security

- backend/server.js
> Comment out import temporarily to run Server

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
> Make body of bfs dfs pages consistent

- .github/workflows/autolabeler.yml
> ADD CICD Workflow for automatic assigning labels to the new created issue

- src/app/components/login-page/login-page.component.html
> fixed the overlapping to container and text at login interface

- src/app/components/login-page/login-page.component.css
- src/app/components/login-page/login-page.component.html
#143 
This PR adds a Google login option to the login page and adjusts the size of the "Go Back" button.
> Add Google Login Option

- backend/models/graphanalysis.js
- backend/models/weightedgraph.js
- backend/server.js
> Graphanalysis

- src/app/components/aboutUs-page/aboutUs.component.css
- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/main-index/main-index.component.css
Removed 500+ lines of unsed code
> Increase Code efficiency, Refactoring code, removing all css code lines which are unused

- src/app/components/header/header.component.html
This pull request implements a feature that allows users to click on the logo in the navigation bar to be redirected to the home page. This enhances user experience by providing an intuitive way to return to the homepage from any section of the website.
New feature
I have performed a self-review of my code.
I have read and followed the Contribution Guidelines.
I have tested the changes thoroughly before submitting this pull request.
I have provided relevant issue numbers, screenshots, and videos after making the changes.
I have commented my code, particularly in hard-to-understand areas.
https://github.com/user-attachments/assets/41bc803c-0d06-4baa-8368-e8a5fd8d5040
The project includes:
A clickable logo in the navigation bar.
Redirection to the homepage when the logo is clicked.
Updated …
> Added Logo Redirect to Home Page

- src/app/components/header/header.component.html
This pull request implements a feature that adds clickable social media links (Twitter, Facebook, LinkedIn) to the website footer. These links redirect users to the respective social media platforms, enhancing the website’s connectivity and user interaction with external platforms.
New feature
I have performed a self-review of my code.
I have read and followed the Contribution Guidelines.
I have tested the changes thoroughly before submitting this pull request.
I have provided relevant issue numbers, screenshots, and videos after making the changes.
I have commented my code, particularly in hard-to-understand areas.
https://github.com/user-attachments/assets/f5c57c42-96cb-47c7-9a4d-5337cede4a43
The project includes:
Addition of social media text links (Twitter, Facebook, LinkedIn) in the …
> Make Footer Interactive with Social Media Links

- README.md
Added all Contributors.
Completed #75
> Added All Contributors | Issue #75

- src/app/components/login-page/login-page.component.ts
- src/styles.css
I have customise the Scrollbar of the webapp that now matches with the theme of the webapp and also added temp. Google Auth to get rid of err.
completed #117
> Customise the WebApp Scrollbar | Added Temp. Google Auth | Issue #117

- src/index.html
I have a BackToTop Button with Smoth Scrolling that enhance UI and UX.
Completed #116 
https://github.com/user-attachments/assets/2e8476d2-1dac-4177-b88c-0aff6018f602
> Added B2T with Smooth Scrolling | Issue #116

- src/app/components/login-page/login-page.component.css
- src/app/components/login-page/login-page.component.html
Closes #154 
This pull request adds a "Remember Me" checkbox to the login form, providing users with an enhanced and familiar interface. 
Feature enhancement
https://github.com/user-attachments/assets/dc99dbd1-4c82-4caa-87bf-2b3213469dbf
I have performed a self-review of my code.
I have read and followed the Contribution Guidelines.
I have tested the changes thoroughly before submitting this pull request.
I have provided relevant issue numbers, screenshots, and videos after making the changes.
I have commented my code, particularly in hard-to-understand areas.
> Add "Remember me" checkbox in login form

- src/app/components/header/header.component.html
#160 
added language translator for english hindi french german and spanish
working demo video:
https://github.com/user-attachments/assets/891bf545-78ba-479b-8e54-6dfc66ec0982
> added language translator 

- backend/.env
i updated JWT implementation which was implemented before and also updated .env file. please also add the labels of gssoc-ext  issue #63
> the JWT implemented and updated .env file

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
- src/app/components/header/header.component.ts
- src/app/components/header/style.css
1. Improved responsiveness for mobile and desktop navbar usability.
2. Enhanced accessibility features for better user experience.
3. Refactored code for improved readability and maintainability.
4. Fixed rendering bugs in mobile navbar interactions.
https://github.com/user-attachments/assets/060e9770-fa90-4c02-b920-75a983b7d102
> [Fix]: Updated responsive navbar feature #172

- src/app/components/header/header.component.html
- src/app/components/header/style.css
A discussion forum enhances user engagement, promotes knowledge sharing, and fosters community building. It enables collaborative problem-solving, generates user-driven content, and provides a platform for real-time updates on graph algorithms. Additionally, it improves website traffic and retention through dynamic discussions and networking opportunities among users.
> Added Discussion Forum

- src/app/app.routes.ts
- src/app/components/header/header.component.html
- src/app/components/navbar/navbar.component.html
- src/app/components/quiz/quiz.component.css
- src/app/components/quiz/quiz.component.html
- src/app/components/quiz/quiz.component.spec.ts
- src/app/components/quiz/quiz.component.ts
- src/app/components/realworld/realworld.component.css
- src/app/components/realworld/realworld.component.html
- src/app/components/realworld/realworld.component.spec.ts
- src/app/components/realworld/realworld.component.ts
Hey @sakeel-103 please merge PR #187 as this is the child branch of quiz so there would be no conflicts in merging
fix: #166
> Real  world

- src/app/components/navbar/navbar.component.html
- src/index.html
the chatbot has been added and its working as expected.
Uploading Screen Recording 2024-10-14 at 12.42.15 PM.mov…
> added chatbot issue#179 solved

- src/app/components/header/header.component.html
- src/index.html
#164 
I have added language translator with more languages including Indian languages. Also, i have fixed the deployment issues now the language translator will be available throughout and working 
https://github.com/user-attachments/assets/d3a7fb7b-7434-4847-b5d4-3883d4f11ba6
examples- 
telgu 
urdu
korean
etc
> added language translator with more languages including Indian languages 

- src/app/components/header/header.component.html
This update introduces a newsletter subscription feature in the footer of the website, allowing users to easily subscribe by entering their email address and clicking the subscribe button. This feature enhances user engagement by keeping subscribers informed about updates and news.
User-Friendly Form: Simple email input field for easy subscriptions.
Responsive Design: Adapts to different screen sizes for accessibility on all devices.
Immediate Interaction: Users can quickly subscribe with a clear call-to-action button.
Centralized Location: Positioned in the footer for easy visibility without cluttering the main content.
> Newsletter Subscription Form for Website Footer

- src/app/components/faq/faq.component.html
- src/app/components/faq/faq.component.ts
> Add navbar to FAQ page

- src/app/components/login-page/login-page.component.css
- src/app/components/signup-page/signup-page.component.css
@sakeel-103 , Issue #181 is fixed now, and you can view it responsively on both large and small screens.
https://github.com/user-attachments/assets/51fb034d-2b30-497e-966b-a1071c9afa0e
> [Fix]: Made the signup and login forms responsive

- .vscode/settings.json
- src/app/components/header/feedback.html
- src/app/components/header/header.component.html
This issue aims to add a Feedback Form to the website, making it responsive across all devices (mobile, tablet, desktop). The form will allow users to submit feedback with relevant fields like name, email, rating, and comments. Proper validation should be added, and the form should be styled for a smooth user experience.
Add a Feedback Form with the following fields:
Name
Email
Rating 
Comments
Ensure the form is responsive across all screen sizes
Implement form validation (e.g., required fields, email format)
Include a submit button with an action for form submission
> Add Responsive Feedback Form to the Website

- backend/server.js
- src/index.html
> Added Graph Input from File Support

- README.md
#206 
The Feature Roadmap section is essential for the DFS-BFS Graph Traversal project as it provides a clear and organized outline of planned features and improvements, helping to keep both users and potential contributors informed about the project's direction. By detailing upcoming functionalities and enhancements, this section not only helps to generate excitement and engagement within the community but also serves as a guide for contributors who may want to focus their efforts on specific areas of development. Furthermore, having a timeline for the release of these features establishes transparency and sets expectations, fostering a collaborative environment where users feel encouraged to participate actively. Overall, the roadmap enhances the project's credibility and promotes a …
> ADD a Feature Roadmap section

- src/app/app.routes.ts
- src/app/components/header/header.component.html
- src/app/components/navbar/navbar.component.html
- src/app/components/resources/resources.component.css
- src/app/components/resources/resources.component.html
- src/app/components/resources/resources.component.spec.ts
- src/app/components/resources/resources.component.ts
> Add resouce page

- README.md
#207 
The Testing Instructions section is vital for the DFS-BFS Graph Traversal project as it provides clear guidelines for contributors and users on how to verify the functionality and reliability of both the frontend and backend components. By detailing the testing frameworks used, as well as step-by-step instructions for running tests, this section empowers developers to easily execute and understand the testing process, ensuring that any new features or bug fixes maintain the overall quality of the application. Additionally, a well-defined testing process fosters a culture of accountability and rigor in development, encouraging contributors to write and run tests for their code changes. This not only helps to identify issues early in the development cycle but also enhances …
> ADD Testing Instruction Section in README

- README.md
- Closes: #226 
Table of Contents
A Table of Contents (ToC) provides a quick navigation guide for users, especially in lengthy documents. By allowing readers to jump directly to specific sections, the ToC improves the overall user experience. It helps users quickly locate information, making the README more efficient and user-friendly, especially for newcomers who may not be familiar with the project.
Changelog
Including a Changelog is essential for tracking the evolution of your project. It documents all significant changes made across different versions, such as bug fixes, new features, and improvements. This transparency allows users and contributors to understand the history of the project, see what has been addressed or added over time, and decide whether to upgrade based on their …
> ADD TABLE OF CONTENT ,CHANGELOG ,TECHNICAL STACK on README file

- README.md
#225 Title : **ADD license and API Documentation on the README **
Importance of License
Including a license is crucial as it informs users and contributors about how they can legally use, modify, and distribute your project. It protects both the creator's rights and the users’ rights, ensuring clarity about what is permitted. Without a license, others may be uncertain about their rights regarding the code, which can deter potential contributors and users. The MIT License, for instance, allows for flexibility in usage while requiring attribution, fostering collaboration and open-source development.
Importance of API Documentation
API documentation is equally important as it provides a clear and structured way for developers to understand how to interact with your application’s backend …
> ADD license and API Documentation on the README 

- src/app/components/header/header.component.html
@sakeel-103 
Keep it simple with the website and added more animations to the footer section for increased interactivity. Format and documentation and link redirection has not been affected. 
Thank you for your time. Good Day!
> Made the footer section more dynamic with animations

- .gitignore
- backend/package-lock.json
- backend/package.json
- backend/server.js
- src/app/app.routes.ts
- src/app/components/contact-us/contact-us.component.css
- src/app/components/contact-us/contact-us.component.html
- src/app/components/contact-us/contact-us.component.spec.ts
- src/app/components/contact-us/contact-us.component.ts
- src/app/components/navbar/navbar.component.html
- src/app/services/auth.service.ts
fix:#221
added ContactUs page
navbar:
page:
Task complited @sakeel-103
> fix:#221/contactus

- src/app/app.routes.ts
- src/app/components/contributors/contributors.component.css
- src/app/components/contributors/contributors.component.html
- src/app/components/contributors/contributors.component.spec.ts
- src/app/components/contributors/contributors.component.ts
- src/app/components/header/header.component.html
- src/app/components/navbar/navbar.component.html
> Add git contributors to the page

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
> Added real time path trace for bfs & dfs

- src/app/components/navbar/navbar.component.ts
> Close dropdown when clicked anywhere on page

- src/index.html
> Replace default favicon

- src/app/footer/footer.component.html
- src/index.html
> Fix typo text in footer

- src/app/components/header/header.component.html
#183 Bro can you check if this working fine because in my system your project is not running if any change is needed then tell me it should look like this, 
https://github.com/user-attachments/assets/8ed98bea-34f8-47fd-94c9-edc613033c57
> enhanced the Hero section of the project

- src/app/components/main-index/main-index.component.css
- src/app/components/main-index/main-index.component.html
- src/app/components/realworld/realworld.component.css
- src/app/components/resources/resources.component.css
fixes:#256 
fixes:#254
this pullrequest Enhance the User Interface , Finding the code and reading the code to correctiond leads to lot time , appears simple but not and also Mainindex page in
before : 
https://github.com/user-attachments/assets/08cd08ad-9c33-4c16-9d80-852ebf9e1871
after:
Uploading open1.mp4…
before:
after:
https://github.com/user-attachments/assets/903c9483-d460-4184-8d57-cfbd204f1470
> Fixes:#256 invisible words with white background.

- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
> Added download button in dfs/bfs pages

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
- src/app/components/header/header.component.ts
This pull request addresses issues in the BFS and Dijkstra's algorithms:
- Fixed BFS to handle edge cases in empty graphs.
- Updated Dijkstra's algorithm to manage negative weights.
- Added unit tests to ensure correctness.
Please review the changes and let me know if further modifications are needed.
https://github.com/user-attachments/assets/fbcb8bca-5e78-4492-bd63-d9ed9765fd10
> Fix BFS and Dijkstra's algorithm issues

- src/app/components/header/header.component.html
Add Bellman-Ford and Floyd-Warshall algorithm
fix issue #287
> Add more algorithms in Master Key Graph Algorithms 

- src/app/components/login-page/login-page.component.css
- src/app/components/login-page/login-page.component.html
> Re-aligned check-box

- src/app/app.routes.ts
- src/app/components/header/header.component.html
- src/app/components/navbar/navbar.component.html
- src/app/components/reviews/reviews.component.css
- src/app/components/reviews/reviews.component.html
- src/app/components/reviews/reviews.component.spec.ts
- src/app/components/reviews/reviews.component.ts
I have kept it minimilistic and tried making it functional
> Add review and questions page

- contributor/contributor.css
- contributor/contributor.html
- contributor/contributor.js
- src/index.html
@sakeel-103 can you please review this , its working.
#298 
https://github.com/user-attachments/assets/7ac7b501-36c7-497a-8bed-3c90fe33939b
> contributors page has been added.

- src/app/components/header/header.component.html
- src/app/components/header/style.css
@sakeel-103  Improve the UI of the Graph algo section by adding some hover effect and make more engaging .
issue number -#294
before:
after:
> improve the UI of graph algo section

- src/app/components/navbar/navbar.component.css
- src/app/components/navbar/navbar.component.html
fixes:#308 
this PR makes sure that , logo is added to main-index-page as well .
> Fixes: #308 jashwanth/IcontoIndex

- src/app/components/header/header.component.html
- src/app/components/header/style.css
Issue no -  #295 
I improve the font color of graph algo  now font is more visible and more attractive . 
before:
after:
> improve the font coloring of graph algo section.

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
- src/app/components/main-index/main-index.component.html
- src/app/components/navbar/navbar.component.html
- src/app/components/resources/resources.component.css
Fixes:#302
This pull request enhances the interface of the resources page additional resources.
https://github.com/user-attachments/assets/0e2c1186-6fa9-4a3d-a3bc-d779575a45b2
> Fixes:#302-Jashwanth/resource

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
- src/app/components/main-index/main-index.component.html
- src/app/components/navbar/navbar.component.html
Fixes:#301
This PR make sure that , Onclick of learn more will travers to resourcses page and also make sure that correction of the css of the navbar , which was not working in last commit.
https://github.com/user-attachments/assets/43cc01cb-ce8c-47fb-abbb-d6634cd179f7
> Fixes: #301 - Jashwanth/learnmore

- src/app/components/contributors/contributors.component.css
- src/app/components/faq/faq.component.css
- src/app/components/faq/faq.component.html
- src/app/components/reviews/reviews.component.css
Fixes: #303 
this PR makes sure that , Theme correction has been done , which is more attractive and premium.
contributors-page:
https://github.com/user-attachments/assets/c783a5a6-f3d9-43f4-8dd2-c2337c4bd727
Faq-page:
https://github.com/user-attachments/assets/04a9459e-a075-4f5a-95e1-6e33edaaa486
review-page:
https://github.com/user-attachments/assets/2402729e-a46f-4339-9a23-1975b56b6d1f
> Fixes: #303 - Jashwanth/faq/contributor/review

- src/app/components/login-page/login-page.component.css
- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
Fixes:#304
This PR make sure that we have made Validation for login page , 
https://github.com/user-attachments/assets/06ae26a5-8bd4-42b8-909b-cad3b5dee47e
> Fixes:#304-jashwanth/LoginPage

- src/app/components/header/header.component.html
- src/app/components/header/style.css
Issue no - #296 
Improve the Ui of discussion forum and try to match with website theme.
before:
after:
> improve UI of discussion forum.

- backend/server.js
- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
- src/app/components/signup-page/signup-page.component.ts
- src/app/services/auth.service.ts
> Added user authetication with Mongodb

- src/index.html
issue #315 
Added more Indian language to google translator !!
> Added more indian language

- src/app/app.routes.ts
- src/app/components/navbar/navbar.component.html
- src/app/components/page-not-found/page-not-found.component.css
- src/app/components/page-not-found/page-not-found.component.html
- src/app/components/page-not-found/page-not-found.component.spec.ts
- src/app/components/page-not-found/page-not-found.component.ts
> ADD: Page404

- src/index.html
> replaced windows alert with toast notification

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
- src/app/components/header/style.css
- src/app/components/navbar/navbar.component.css
Hi @sakeel-103
I recently updated the navbar menu for your project to make it more attractive and user-friendly. These simple yet impactful design updates enhance readability, improve navigation, and give your site a visually appealing touch that stands out. I contributed to this enhancement to improve the overall design.
Best regards,
Issue #330 
@khurshed07
https://github.com/khurshed07
> modify navbar menu design

- contributor/contributor.css
- contributor/contributor.html
- src/index.html
#329 
1- Somebody copy pasted contributor page of buddy trail project here 
so i changed the code
2- add toast notification system
3- linked the page to main index file
4 - and enhanced the css
> Enhanced the Contributor page

- src/app/components/header/header.component.html
- src/app/components/header/style.css
I have redesigned the discussion forum with the Proper Responsiveness
https://github.com/user-attachments/assets/cb2bf4cd-9e43-497c-8722-e0a6878cd697
https://github.com/user-attachments/assets/7f234e3e-4d8e-483a-81d0-9b1657e781f7
Completed #318
> Redesigning of Dicuss Forum with Responsiveness | Issue #318

- src/app/components/login-page/login-page.component.css
- src/app/components/login-page/login-page.component.html
- src/app/components/signup-page/signup-page.component.css
- src/app/components/signup-page/signup-page.component.html
- src/app/components/signup-page/signup-page.component.ts
I have completed the taks mentioned in #73 
Before :
After
https://github.com/user-attachments/assets/5bd3aa2e-c179-4b83-8144-57f1da222132
Completed #73
> Enhances the Styling in SIgnIn and SignUp Pages, also added Email Validation | Issue #73

- src/index.html
I have redesigned the footer and also added responsiveness in the footer.
Before and After :
https://github.com/user-attachments/assets/dcc0bdf3-3210-4ff5-8004-105050594601
Completed #319
> Redesigning of Footer and Responsiveness Addition | Issue #319

- src/app/components/header/header.component.html
Add feature visualizer in  algorithms when in master key algo section click any algo then in visualizer show algo visualization
fix issue #342
https://github.com/user-attachments/assets/0f28b301-f76d-4625-ac68-2b501a6f65a8
> [Feature]: Add visualization

- src/app/components/signup-page/signup-page.component.ts
Description:
This PR make sure that After once signin redirect to home page , and also user can logout and login.
https://github.com/user-attachments/assets/d0c53a12-8cbb-4517-a0a2-b4babb7f14d1
> Fixes:#321 After once signin redirect to home page , 

- src/app/components/header/header.component.html
> Improved UI of Interactive Graph Visualizer

- src/index.html
#193 
working demo
https://github.com/user-attachments/assets/50139d79-4c5f-4501-8900-61943a4e9c0d
> added contact us popup modal at footer - done the fixes

- src/index.html
Fixes:#351
this PR makes sure that this added the small model and enhanced UI .
https://github.com/user-attachments/assets/32507572-101e-4264-8c76-b7341e97e86d
> Fixes: #351 - Added the small screen to select language 

- src/app/components/header/header.component.html
- src/app/components/header/style.css
Improve the issue of inconsistence font styling . 
issue no - #352 
before:
after:
> improve the UI of the Interactive section.

- src/app/components/faq/faq.component.css
- src/app/components/faq/faq.component.html
- src/app/components/faq/faq.component.ts
> enhanced FAQ page

- src/app/components/bfs-page/bfs-page.component.ts
#336 
Replaced all alert calls with a showToast method that you can implement to display toast notifications.
> Replaced all alert calls with a showToast method

- .github/workflows/ci-cd.yaml
#364
. The .ci-cd.yaml file will run tests, build the Angular frontend, and ensure the Node.js/Express backend is running smoothly. This workflow assumes you are using GitHub Actions for CI/CD and Netlify for deployment.
> added ci-cd workflow

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
- src/app/components/header/header.component.ts
I have added DFS and Dijkstra's algo visualizer in the Interactive Graph Visualizer section of home page. 
Issue no. - #326 
Before:
After:
https://github.com/user-attachments/assets/952c28b6-b029-4cf9-a55c-6da9a6090fa8
> added visualizations for dfs and dijkstra algo and buttons to display them

- package.json
- src/app/app.routes.ts
- src/app/components/algocompare/algocompare.component.css
- src/app/components/algocompare/algocompare.component.html
- src/app/components/algocompare/algocompare.component.spec.ts
- src/app/components/algocompare/algocompare.component.ts
- src/app/components/navbar/navbar.component.html
> Add algo compare Page

- src/app/components/roadmap/roadmap.component.css
- src/app/components/roadmap/roadmap.component.html
- src/app/components/roadmap/roadmap.component.spec.ts
- src/app/components/roadmap/roadmap.component.ts
> Add roadmap page to the application

- src/app/components/algo-search/algo-search.component.css
- src/app/components/algo-search/algo-search.component.html
- src/app/components/algo-search/algo-search.component.spec.ts
- src/app/components/algo-search/algo-search.component.ts
fix: #362 
**This page has** 
1. Depth-First Search (DFS)
2. Breadth-First Search (BFS)
3. Dijkstra's Algorithm
4. A Search Algorithm*
5. Bellman-Ford Algorithm
6. Floyd-Warshall Algorithm
7. Prim's Algorithm
8. Kruskal's Algorithm
9. Topological Sorting
10. Greedy Best-First Search
> Add Serachable Algorithm Page 

- package-lock.json
- package.json
- src/app/app.routes.ts
- src/app/components/profile/profile.component.css
- src/app/components/profile/profile.component.html
- src/app/components/profile/profile.component.spec.ts
- src/app/components/profile/profile.component.ts
fix: #241 
**This page has featues that are** 
1. User profile header
2. Level and rank display
3. XP progress bar
4. Streak count
5. Questions solved counter
6. Achievements list
7. Recent activities log
8. Performance radar chart
9. Responsive grid layout
10. Avatar display
11. Visual icons for stats and achievements
For now the data is static will improve to dynamic when project would be designed
> Add Profile Page to the application

- src/app/components/Graphs/directedgraph.html
- src/app/components/header/header.component.html
#385 
demo - https://www.loom.com/share/64653629e2d741f495ac052ca2f1e69f?sid=8f638115-8f6b-4034-b226-a14ec274325e
> added directed graph page

- src/app/components/Graphs/undirectedgraph.html
- src/app/components/header/header.component.html
> added undirected graph page

- src/app/components/login-page/login-page.component.css
- src/app/components/login-page/login-page.component.html
- src/app/components/signup-page/signup-page.component.css
- src/app/components/signup-page/signup-page.component.html
Closes #191 
Improved login and signup page UI Matching the original site UI
> Improved login/signup page matching sites UI

- src/index.html
#169 done i am unable to provide you a video because this project is not running in my system but I have  only changed the footer CSS not deleted any logic
> enhanced the footer added transitions and effects #169

- src/index.html
- src/styles.css
#305 done adding testimonials ( reviews section )
> Created the Testimonials section 

- README.md
added Stargazers and Forkers section to readme.md
PR Description
added Stargazers and Forkers section to readme.md
fixes #413 
close #413 
Change
added Stargazers and Forkers section to readme.md
Stargazers
Use Case:
1. Bookmarking Projects
2. Discovering Popularity
Benefits:
1. Visibility
2. Feedback Indicator
3. Community Engagement
Forkers
Use Case:
1. Creating Personal Copies
2. Contributing Back
Benefits:
1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership
> Update README.md added Stargazers and Forkers section to readme.md 

- src/app/components/Graphs/weightedgraph.html
- src/app/components/header/header.component.html
> added weighted graph visualizer page

- src/app/components/quiz/quiz.component.css
I have added more questions to the question section for the BFS and DFS algorithms. These questions are aimed at helping users better understand and practice these algorithms. Fixes #414 . Please review and let me know if any additional changes are needed.
> Added Question Section for BFS and DFS algorithms

- src/app/components/Graphs/tree.html
- src/app/components/header/header.component.html
> added tree visualization page

- .github/scripts/generate_structure.py
- .github/workflows/update-structure.yml
> automated python project structure

- .github/scripts/generate_structure.py
- .github/workflows/update-structure.yml
- src/index.html
#182  enhanced the footer adding icons and transitions effects
> Footer update

- src/app/components/header/header.component.html
- src/app/components/navbar/navbar.component.html
- src/index.html
Fixes: #419
- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.
> Created a new chatbot according to theme !!

- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.ts
- src/app/components/faq/faq.component.ts
- src/app/components/header/header.component.html
- src/app/components/login-page/login-page.component.html
- src/app/components/navbar/navbar.component.html
- src/app/components/quiz/quiz.component.ts
- src/app/components/reviews/reviews.component.ts
- src/index.html
Fixes: #425 
Added title in the titlebar according to the pages like
GraphExplorer Pro | FAQ,
GraphExplorer Pro | BFS
GraphExplorer Pro | DFS
GraphExplorer Pro | Reviews etc...
And some of the pages were not accesible , ie they are not yet created or hosted !!
> Changed Title in the Titlebar according to the pages !!!

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.ts
- src/app/components/faq/faq.component.css
- src/app/components/faq/faq.component.ts
- src/app/components/header/header.component.html
- src/app/components/login-page/login-page.component.html
- src/app/components/navbar/navbar.component.css
- src/app/components/navbar/navbar.component.html
- src/app/components/quiz/quiz.component.css
- src/app/components/quiz/quiz.component.ts
- src/app/components/realworld/realworld.component.css
- src/app/components/resources/resources.component.css
- src/app/components/reviews/reviews.component.css
- src/app/components/reviews/reviews.component.ts
- src/app/components/roadmap/roadmap.component.css
- src/index.html
- src/styles.css
> Implemented a new font style for the website to enhance interactivity and engagement.

- src/app/components/bfs-page/bfs-page.component.css
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.css
- src/app/components/dfs-page/dfs-page.component.ts
- src/app/components/faq/faq.component.css
- src/app/components/faq/faq.component.ts
- src/app/components/header/header.component.html
- src/app/components/login-page/login-page.component.html
- src/app/components/navbar/navbar.component.css
- src/app/components/navbar/navbar.component.html
- src/app/components/quiz/quiz.component.css
- src/app/components/quiz/quiz.component.ts
- src/app/components/realworld/realworld.component.css
- src/app/components/resources/resources.component.css
- src/app/components/reviews/reviews.component.css
- src/app/components/reviews/reviews.component.ts
- src/app/components/roadmap/roadmap.component.css
- src/index.html
- src/styles.css
Fixes: #407
Added icons in the navbar !!
> Added Icons to the Navbar !!

- src/index.html
> add popup faq modal at footer 

- src/app/components/Graphs/acyclicgraph.html
- src/app/components/Graphs/directedgraph.html
- src/app/components/Graphs/tree.html
- src/app/components/Graphs/undirectedgraph.html
- src/app/components/Graphs/weightedgraph.html
fixes #454 
similar to all pages
working demo:
https://www.loom.com/share/cbf3d668727a406bbb859f1da28dad63?sid=5b4d75bb-f57e-449e-be10-7eea693bc3c3
> added back to top button at all graph pages

- CONTRIBUTING.md
Fixes: #442
I've added the contribution.md file that to including a dedicated section for project organization, a detailed pull request process, and clearer guidelines for issue reporting. I hope you find these changes beneficial.
Could you please add the labels "gesso-ext" . Thankyou !
> FIXES #442 Documentation: UPDATE Of Contributing.md

- src/app/components/header/header.component.html
- src/app/components/header/style.css
- src/index.html
Fixes: #445 
Fixed button color issue and improve hover styling.
Also fixed missing tags in html part.
> Fixed missing tags, alignment and button color issue.

- src/app/components/reviews/reviews.component.css
- src/app/components/reviews/reviews.component.html
- src/app/components/reviews/reviews.component.spec.ts
- src/app/components/reviews/reviews.component.ts
Fixes: #462 
This pull request introduces several enhancements to the ReviewsComponent:
1. File Upload for Questions: Users can now attach images or documents when asking questions. This enhances the context for discussions.
2. Image Preview: The component now supports displaying uploaded images next to questions, providing a better user experience.
3. Testing Improvements:
- Added comprehensive unit tests for the review, question, and reply submission functionalities.
- Included tests for file selection and image URL generation, ensuring reliability and functionality of the new features.
- Updated the component and its template to accommodate the new file upload functionality and image previews.
- Enhanced overall structure and readability of the code.
- These changes aim to improve user …
> Enhance Review Component: Add Question/Reply Functionality and File Upload Feature

- src/app/components/quiz/quiz.component.css
- src/app/components/quiz/quiz.component.html
- src/app/components/quiz/quiz.component.ts
Fixes: #412
- Added quiz section .
- create score card with score and correct answer.
- Provide better analysis of all the quiz questions.
> Added Quiz for DFS BFS Graph Travers

- src/index.html
Fixes: #346 
I have added the progressbar that that represent the Current height/Depth of the webpage. 
https://github.com/user-attachments/assets/b0e200cf-179d-4e25-a0a1-6d9f65500237
> Added ProgressBar | Issue #346

- src/app/components/faq/faq.component.html
Fixes: #465
- **Feature Enhancement**: Improved the FAQ page to provide a more user-friendly and visually appealing experience.
- **Key Changes**:
- Redesigned the layout for better readability and navigation.
- Implemented collapsible sections for each question, allowing users to expand or collapse answers as needed.
- Enhanced styling to align with the overall theme of the website, making the page more attractive and consistent.
- Added search functionality to allow users to quickly find specific questions and answers.
- **Project Enhancement**: These improvements enhance user engagement by making information more accessible and visually appealing, thus contributing to a better overall user experience.
> Enhancing the FAQ page !!!

- src/app/components/Graphs/acyclicgraph.html
- src/app/components/Graphs/directedgraph.html
- src/app/components/Graphs/tree.html
- src/app/components/Graphs/undirectedgraph.html
- src/app/components/Graphs/weightedgraph.html
Fixes: #453 
added g-language translators 
Include screenshots or GIFs to demonstrate your changes
> added gtranslator to graph visualizer page

- src/app/components/header/header.component.html
Fixes: #468
Added algorithms in the master key algorithms page !!!
> Added Algorithms !!!

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
- src/app/components/practice/practice.component.ts
- src/index.html
Fixes: #470 
https://github.com/user-attachments/assets/97b34966-b780-4b4d-961e-259298395a83
This update introduces a curated list of additional graph-related problems to the practice skills section. Each problem includes a brief description and a direct link to its corresponding GeeksforGeeks page, enabling easier access for users to enhance their algorithmic skills. This enhancement aims to provide a broader range of practice opportunities for users interested in mastering graph theory and its applications.
> Enhanced Practice Skills Section with Additional Graph Problems

- README.md
This update introduces a more efficient way to manage our README by implementing automatic updates for table metrics, a contributors scroller, and dynamically updating images. Previously, these elements had to be manually inserted, which was time-consuming and prone to errors.
- Table Metrics: Integrated automatic table metrics to reflect real-time data.
- Contributors Scroller: Added a scroller to showcase contributors dynamically.
- Dynamic Images: Implemented a system for images to update automatically, ensuring the README always displays the most current visuals.
- Efficiency: Reduces manual workload, allowing for more time to focus on development.
- Accuracy: Minimizes errors associated with manual updates.
- Up-to-Date Information: Ensures that all displayed information is current …
> Added Automatic Table Metrics, Contributors Scroller, and Dynamic Image Updates

- src/app/components/bfs-page/bfs-page.component.html
- src/app/components/bfs-page/bfs-page.component.ts
- src/app/components/dfs-page/dfs-page.component.html
- src/app/components/dfs-page/dfs-page.component.ts
Fixes: #475
- Added Predefined graph selection for bfs/dfs
https://github.com/user-attachments/assets/179ac439-725d-43d7-b6ad-9a7cf9f99b36
> Added Predefined graph selection for bfs/dfs

- src/app/components/header/header.component.html
**Description:**
This PR introduces interactive hover effects to enhance user engagement and visual feedback on the GraphExplorer Pro website. The changes include:
1. **Title Hover Effect**
- **Feature:** Added a smooth scaling effect on hover for the main title.
- **Implementation:** The text size of "Graph Algorithms" increases smoothly when hovered over.
2. **Feature Card Text Color Change**
- **Feature:** Implemented a hover effect for the text in the feature cards.
- **Implementation:** When hovering over a feature card, the corresponding paragraph text changes to dark navy (`#001f3f`).
**Impact:**
These enhancements aim to create a more engaging user experience on the GraphExplorer Pro platform, making it visually appealing and interactive for users as they explore graph algorithms. …
> Improve User Interaction with Hover Effects in GraphExplorer Pro

- src/contact.css
- src/contact.html
- This pull request refers to enhancing the visual appearance of the "Contact Us" page in your contact.html and contact.css files, with  add icons and input field in text field of input. 
- **Icons Added to Input Fields :**
1. Added Font Awesome icons next to input fields for a more intuitive design.
2. Used relevant icons (e.g., envelope for email, phone for contact number) to visually represent the purpose of each field.
- **Styled Input Fields :**
1. Enhanced the appearance of input fields by adding padding, border-radius, and hover effects.
2. Introduced a consistent color scheme that aligns with the overall theme of the website.
- **Responsive Design :**
1. Ensured that the layout is responsive using CSS media queries, so it looks good on all devices, from desktops to mobiles.
2. …
> Enhance-Visual Appearance of Contact-Us page in contact.html and contact.css with  add icons and input field in text field of input.

- src/app/components/realworld/realworld.component.ts
Fixes: #515 
I have added the real world applications based on different categories and added labels under categories !!
> Added Real world applications under different categories !!

- src/app/components/realworld/realworld.component.css
- src/app/components/realworld/realworld.component.ts
Fixes: #514 
I have improved the page and content is visibly clear for users and improved the user experience !!!
> Improving the Real World Applications page !!

- .github/ISSUE_TEMPLATE/Config.yml
Fixes: #502 
- **Feature Description:** This PR incorporates a Q&A Suggestion Template into the project, improving communication and fostering collaboration within the project community. This addition aims to streamline the process of providing feedback, asking questions, and suggesting improvements.
- **Major Changes:** Added a structured Q&A suggestion template to guide users in submitting questions and suggestions effectively.
- **Enhancements:** This feature enhances the project by providing a clear and structured format for user interaction, leading to better project documentation, reduced redundancy, and a more robust, user-friendly system overall.
N/A
> CREATE Q&A Suggestion Template

- src/app/components/header/header.component.html
- src/app/components/realworld/realworld.component.css
- src/app/components/realworld/realworld.component.ts
- src/index.html
Fixes: #511
I have improved the various graphs types section and enhanced its UI and added the content to improve the user experience !!
> Improved the various Graphs types section !!

- src/app/app.routes.ts
- src/app/components/geminibot/geminibot.component.css
- src/app/components/geminibot/geminibot.component.html
- src/app/components/geminibot/geminibot.component.spec.ts
- src/app/components/geminibot/geminibot.component.ts
Fixes: #500 
This PR introduces **Chatbot Gemini**, an advanced conversational AI feature designed to enhance user interaction within the application. The major changes include:
- Integration of the Gemini chatbot, providing users with 24/7 support and engagement through natural language processing.
- Customizable responses and user interaction capabilities to improve user satisfaction.
- Enhanced user experience by enabling quick answers to common queries and facilitating smoother navigation.
By implementing Chatbot Gemini, we aim to provide users with immediate assistance and create a more dynamic and interactive platform.
[Include screenshots or GIFs demonstrating the Chatbot Gemini in action and any UI changes made.]
**Screenshots**
> add chatbot gemini

- src/app/app.module.ts
- src/app/components/contact-us/contact-us/contact.us/contact-us.component.css
- src/app/components/contact-us/contact-us/contact.us/contact-us.component.html
- src/index.html
Fixes: #479 
Implemented an enhanced footer design for improved layout and styling flexibility.
Added modular sections in the footer, allowing individual adjustments for headings and links without affecting other sections.
This enhancement improves readability, consistency, and ease of maintenance for the footer area in the project.
-  I am a participant of GSSoC-ext.
-  I have followed the contribution guidelines of this project.
-  I have viewed deployment of my code.
-  My changes generate no new warnings.
-  I have made this change from my own.
-  My code follows the style guidelines of this project.
- I have performed a self-review of my own code.
-  I have added documentation to explain my changes.
-  This PR is submitted under the GSSoC program.
-  I have taken prior approval for …
> Enhance footer design

- src/app/components/practice/practice.component.css
- src/app/components/practice/practice.component.html
- src/app/components/practice/practice.component.ts
Fixes: #499
I have done the following:-
1. Revamp the Practice Questions Page.
2. Addition of Levels to the Questions.
3. Addition of Filter by Level.
https://github.com/user-attachments/assets/7a24e0ba-3a8e-4f3d-8f47-e7dcbffdbc3b
> Enhance the Practice Questions Page | Issue #499

- package.json
- src/app/components/resources/resources.component.css
- src/app/components/resources/resources.component.html
- src/app/components/resources/resources.component.ts
- src/environments/environment.ts
Fixes: #506 
I have done the following:-
1. Added YT Data Fetch By Youtube API.
2. Added the Filter by Authors/Creators.
3. Enhance the UI and also enhance the cards by fetching and adding the video title. 
4. Added Proper Responsiveness.
https://github.com/user-attachments/assets/d75f16c9-8753-452c-9332-42c66c733a77
> Enhance the Resources Page, Added the YT Data Fetch by API, Added Fiter by Author/Creators | Issuee #506

- src/app/components/code-editor/code-editor.component.css
- src/app/components/code-editor/code-editor.component.html
- src/app/components/code-editor/code-editor.component.ts
Fixes: #505 
I have done the following:-
1. Enhance the Landing UI of Text Editor.
2. Added thems for the Text Editor.
3. Added Multiple Programming and Scripting Languages support in the Text Editor.
https://github.com/user-attachments/assets/52b13632-2f68-429e-9715-5ada81fd9694
> Enhance the Text Editor UI , Added Themes, Added Multi Programming and Scripting Languages | Issue #505

- src/contact.css
- src/contact.html
- src/index.html
Fixes: #437 
Improve styling of footer..
- Bug fix (non-breaking change which fixes an issue)
- [ YES ] I am a participant of GSSoC-ext.
- [ YES ] I have followed the contribution guidelines of this project.
- [ YES ] I have viewed deployment of my code.
- [ YES ] My changes generate no new warnings.
- [ YES ] I have made this change from my own.
- [ YES ] I have taken help from some online resources.
- [ YES ] My code follows the style guidelines of this project.
- [ YES ] I have performed a self-review of my own code.
- [ YES ] I have added documentation to explain my changes.
- [ YES ] This PR is submitted under the GSSoC program.
- [ YES ] I have taken prior approval for this feature/fix.
> Make Footer Styled

- src/app/components/faq/faq.component.css
- src/app/components/faq/faq.component.html
- src/app/components/faq/faq.component.ts
Fixes: #504 
1. Enhance the UI of the FAQs Page.
2. Follows the Angular Component Approach.
3. CleanUp the main index.html file, that contained unnecessary styles and scripts
4. Added Search Bar.
5. Added Toggle Button.
https://github.com/user-attachments/assets/66ac6172-784a-410a-99c6-3db0a0aef41b
> Enhance the FAQs UI | Added Search Bar | Added Toggler | Issue #504

- angular.json
- backend/server.js
- netlify.toml
- src/app/components/login-page/login-page.component.html
- src/app/components/login-page/login-page.component.ts
- src/app/services/auth.service.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Fixes: #331 
- Added Google Sign In method in frontend using gapi
- Updated angular config to allow more than 8kb in build
- Fixed netlify build command
Include screenshots or GIFs to demonstrate your changes
> Added Google Sign In method in frontend using gapi

- src/app/app.routes.ts
- src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.css
- src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.html
- src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.spec.ts
- src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.ts
fix: #545
https://www.loom.com/share/6dc17e2a1ce14a7ea732f8ba3b7c3f1b?sid=96863958-39b5-4e19-8762-61787fd4b06d
> Add maze runner game

- contributor/contributor.css
- contributor/contributor.html
- contributor/contributor.js
- Improved UI elements including email input alignment and resizing.
- Fixed responsive keyframe issue to maintain layout integrity on screen resizing.
- Adjusted CTA box width for better layout balance.
- Enhanced secondary button styling for a more polished appearance.
- Updated input fields with flexbox layout, improved font family, and added margins for better usability.
- Integrated GitHub API data fetching for dynamic repository stats and contributor details.
- Rendered contributor profiles with relevant statistics (total contributions, stars, forks).
- Resolved icon size issues for improved visual consistency.
Dear @sakeel-103 ,
Looking forward to your feedback and hoping this makes the user experience even better! 😊
Everything should now look great on all devices. Feel free to …
> Improve UI and fetch GitHub data for stats and contributors

- src/app/app.routes.ts
- src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.css
- src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.html
- src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.spec.ts
- src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.ts
fix: #545 
https://www.loom.com/share/594e397f83b34a99beaffe8b8471f02e?sid=737b4e31-0e97-4d09-ab39-b52fad84e1e9
> Add tresure hunt game for better understanding of dfs and bfs

- src/app/app.routes.ts
- src/app/components/header/header.component.html
- src/app/components/navbar/navbar.component.html
- src/app/components/sorting-v/sorting.component.css
- src/app/components/sorting-v/sorting.component.html
- src/app/components/sorting-v/sorting.component.spec.ts
- src/app/components/sorting-v/sorting.component.ts
- src/app/components/sorting-v/style.css
Fixes: #447 
ITS INCLUDES ALL THE SORTING ALGORITHM. WE CAN VISUALIZE SORTING ALGORITHMS ..
- New feature (non-breaking change which adds functionality)
https://github.com/user-attachments/assets/86b53bd6-65dd-4bce-aa7f-0e786404c653
- [ YES ] I am a participant of GSSoC-ext.
- [ YES ] I have followed the contribution guidelines of this project.
- [ YES ] I have viewed deployment of my code.
- [ YES ] My changes generate no new warnings.
- [ YES ] I have made this change from my own.
- [ YES ] I have taken help from some online resources.
- [ YES ] My code follows the style guidelines of this project.
- [ YES ] I have performed a self-review of my own code.
- [ YES ] I have added documentation to explain my changes.
- [ YES ] This PR is submitted under the GSSoC program.
- [ YES ] I have …
> SORTING VISUALIZER OF ALL THE SORTIGN ALGORITHEM

- src/app/components/robot/robot.component.html
- src/app/components/robot/robot.component.spec.ts
- src/app/components/robot/robot.component.ts
Robot Navigator
Implementation: Create a grid where a robot must navigate to a target. Use BFS for optimal pathfinding to avoid obstacles, and DFS for testing alternative routes in case of blockages.
https://github.com/user-attachments/assets/a1bb1d95-6317-40c1-a920-0841069d1e04
> Add robot navigation game

- src/app/components/feedback/feedback.component.ts
Fixes: #557 
- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.
> fix feedback url

- src/app/components/resources/resources.component.css
- src/app/components/resources/resources.component.html
Fixes: #564
- Added inline hover effects for resource and video cards.
- Implemented color transitions on hover to improve visual feedback.
- Applied background color changes and scaling effects for interactive feel.
- Introduced shadow transitions for a more dynamic look on card hover.
- Enhanced UI accessibility with improved contrast and responsiveness.
https://github.com/user-attachments/assets/274b0d20-893e-40a5-9c43-177d1d12a74b
> Enhanced UI with inline hover effects, color changes, and shadow transitions for resource and video cards.

- src/app/components/resources/resources.component.css
- src/app/components/resources/resources.component.html
- src/index.html
Fixes: #577
- Custom Cursor Elements: Added HTML elements for the custom cursor, including a small dot and a larger outline.
- CSS Styling: Implemented styles to hide the default cursor and design the custom cursor with smooth animations.
- Cursor Behavior: Positioned the cursor elements dynamically to follow the mouse movement across the page.
- Transition Effects: Added smooth opacity and transform transitions for a fluid cursor experience.
- Compatibility: Ensured the custom cursor does not interfere with interactive elements, maintaining a seamless user experience.
https://github.com/user-attachments/assets/2d0e0b9b-2173-4773-97e6-e3a666e75a5d
>  Adding  Custom Cursor to Website !!!

- src/app/components/header/header.component.css
- src/app/components/header/header.component.html
Fixes: #571
- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.
https://github.com/user-attachments/assets/019ec5cd-8361-4482-9bf3-dec8a8af93c1
> Adding hovering effects to the navabr elements !!

- src/app/components/code-editor/code-editor.component.html
- src/app/components/code-editor/code-editor.component.ts
Fixes: #567
This PR introduces the following updates to the code editor component:
- **Extended Language Support**: Added templates and syntax highlighting for more popular coding languages including TypeScript, Ruby, PHP, Go, Swift, and Kotlin.
- **ACE Mode Configuration**: Updated the ACE editor configuration to handle the new languages with correct syntax modes.
- **Language Templates**: Each new language is pre-populated with a basic code template to help users get started quickly.
- **Dynamic Language Switching**: Users can now easily switch between multiple programming languages in the editor with their respective templates.
This enhancement broadens the versatility of the code editor, supporting a wider range of programming environments. …
> Adding Support for Additional Languages in Code Editor

- src/app/components/reviews/reviews.component.css
- src/app/components/reviews/reviews.component.html
Fixes: #568
- Updated the UI design with a fresh blue and white color scheme to provide a modern and clean aesthetic.
- Applied a blue-to-white gradient background for the main container, enhancing visual appeal.
- Styled review, question, and reply cards with rounded corners and soft shadows, creating a more polished and user-friendly interface.
- Improved form elements (input and textarea fields) with a light blue background on focus to make interactions more intuitive.
- Refined button styles with hover and active effects for a smooth user experience.
- Enhanced the layout's overall responsiveness and consistency across elements.
**Changes:**
- **Gradient Background:** Applied a linear gradient from blue to white for the main container's background.
- **Card Styling:** Updated cards …
> Enhance UI with Blue and White Shades for a Modern, Clean Look For Reviews page !!!

- src/app/app.routes.ts
- src/app/components/forest-explorer/forest-explorer.component.css
- src/app/components/forest-explorer/forest-explorer.component.html
- src/app/components/forest-explorer/forest-explorer.component.spec.ts
- src/app/components/forest-explorer/forest-explorer.component.ts
fix: #545
Forest Explorer
Implementation: Create a forest grid where nodes represent trees. Use DFS to explore deep into the forest for specific objectives (like finding a rare plant), while BFS is used to find paths to nearby objectives or exits.
https://www.loom.com/share/1eafe4125cc34615a4de354e07b0b6de?sid=f193a32a-610a-44c2-bdfb-8e5c3dccd9cf
> Add forest game to the application 
